- name: Update EC2 instance and install package
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_name: "{{ target_instance }}"
    package_name: "{{ package_name }}"
    region: "{{ region }}"
  tasks:
    - name: Get the instance information
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ instance_name }}"
      register: instance_info

    - name: Fail if no instance found
      fail:
        msg: "No instance found with name '{{ instance_name }}' in region '{{ region }}'."
      when: instance_info.instances | length == 0

    - name: Set instance ID variable
      set_fact:
        instance_id: "{{ instance_info.instances[0].instance_id }}"

    - name: Update the instance name tag
      amazon.aws.ec2_tag:
        region: "{{ region }}"
        resource: "{{ instance_id }}"
        state: present
        tags:
          Name: "{{ instance_name }}-updated"

    - name: Install package on the selected instance
      ansible.builtin.command:
        cmd: "ssh -i ~/.ssh/jenkinskey.pem ubuntu@{{ instance_info.instances[0].public_ip_address }} 'sudo apt update && sudo apt install -y {{ package_name }}'"
      args:
        warn: false