- name: Update AWS resources
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    region: us-east-1
    security_group_id: sg-03907cedf72731f32
    security_group_name: "Updated_SG"
    security_group_description: "Updated security group for EC2 instances"
    new_instance_name: "Updated-EC2-Instance"
    ec2_instance_id: i-0ec33002303a55643

  tasks:
    - name: Update Security Group - Add rule to allow HTTPS traffic
      amazon.aws.ec2_security_group:
        group_id: "{{ security_group_id }}"
        name: "{{ security_group_name }}"  
        description: "{{ security_group_description }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        state: present
      register: sg_update_result

    - name: Display Security Group Update Result
      debug:
        var: sg_update_result

    - name: Update EC2 Instance Name
      amazon.aws.ec2_tag:
        resource: "{{ ec2_instance_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ new_instance_name }}"
      register: ec2_tag_update_result

    - name: Display EC2 Instance Tag Update Result
      debug:
        var: ec2_tag_update_result
