- name: Update AWS resources
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    region: us-east-1
    security_group_id: "{{ security_group_id }}"
    new_instance_name: "{{ new_instance_name }}"
    ec2_instance_id: "{{ ec2_instance_id }}"

  tasks:
    - name: Update Security Group - Add rule to allow HTTPS traffic
      amazon.aws.ec2_security_group:
        group_id: "{{ security_group_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        state: present
      register: sg_update_result

    - name: Display Security Group Update Result
      debug:
        var: sg_update_result

    - name: Update EC2 Instance Name
      amazon.aws.ec2_tag:
        resource: "{{ ec2_instance_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ new_instance_name }}"
      register: ec2_tag_update_result

    - name: Display EC2 Instance Tag Update Result
      debug:
        var: ec2_tag_update_result
