- name: Update EC2 instance and install package
  hosts: webservers
  gather_facts: no
  vars:
    instance_name: "{{ target_instance }}"
    package_name: "{{ package_name }}"
    region: "{{ region }}"
  tasks:
    - name: Get the instance information
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ instance_name }}"
      register: instance_info

    - name: Fail if no instance found
      fail:
        msg: "No instance found with name '{{ instance_name }}' in region '{{ region }}'."
      when: instance_info.instances | length == 0

    - name: Set instance ID variable
      set_fact:
        instance_id: "{{ instance_info.instances[0].instance_id }}"

    - name: Update the instance name tag
      amazon.aws.ec2_tag:
        region: "{{ region }}"
        resource: "{{ instance_id }}"
        state: present
        tags:
          Name: "{{ instance_name }}-updated"
      delegate_to: localhost

    - name: Install package on the selected instance
      ansible.builtin.yum:
        name: "{{ package_name }}"
        state: present
      delegate_to: "{{ instance_name }}"



