- name: Provisioning S3 Bucket using Ansible playbook
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    aws_region: us-east-1
    bucket_name: "myansibles3bucket312-{{ 100 | random }}"

  tasks:
    - name: Check if bucket already exists
      amazon.aws.s3_bucket_info:
        region: "{{ aws_region }}"
        name: "{{ bucket_name }}"
      register: bucket_info
      ignore_errors: yes

    - name: Create S3 bucket if it doesn't exist
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        region: "{{ aws_region }}"
        versioning: yes
        tags:
          name: myansiblebucket
          type: example
      when: bucket_info.buckets is not defined or bucket_info.buckets | length == 0
      register: s3_result
      ignore_errors: yes

    - name: Display S3 bucket creation result
      debug:
        var: s3_result
        verbosity: 2

    - name: List all S3 buckets
      amazon.aws.s3_bucket_info:
      register: all_buckets
      ignore_errors: yes

    - name: Display all S3 buckets
      debug:
        var: all_buckets.buckets
        verbosity: 1
