- name: Provisionner une instance EC2
  hosts: localhost
  gather_facts: no
  vars:
    instance_type: t2.micro
    ami_id: ami-0e86e20dae9224db8  # Remplacez par un AMI valide pour votre région
    region: us-east-1
    keypair: key  # Remplacez par votre paire de clés
    security_group: ansible-security-group  # Remplacez par votre groupe de sécurité

  tasks:
    - name: Lancer une nouvelle instance EC2
      amazon.aws.ec2_instance:
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        wait: yes
        region: "{{ region }}"
        security_groups: "{{ security_group }}"
        count: 1
        tags:  # Correct parameter for tagging instances
          Name: "Jenkins-Ansible-EC2"
          Environment: "Development"
      register: ec2

    - name: Afficher les informations sur les instances créées
      debug:
        var: ec2