- name: "Delete RDS instance"
  hosts: localhost
  vars: 
    DB_ID: "CFI-validator-db"
    DB_AWS_REGION: "us-east-1"
    
  tasks:
    - name: Delete the RDS instance
      community.aws.rds_instance:
        aws_region: "{{ DB_AWS_REGION }}"
        db_instance_identifier: "{{ DB_ID }}"
        state: absent
        skip_final_snapshot: true

      register: dbdetails

    - name: Print the details of the deleted database
      debug:
        var: dbdetails
