- name: Manage S3 Bucket
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    bucket_name: "{{ bucket_name }}"

  tasks:
    - name: Delete an S3 bucket
      community.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: absent
      register: result

    - name: Debug the result
      debug:
        var: result
