- name: List AWS EC2 instances
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get information about EC2 instances
      amazon.aws.ec2_instance_info:
        region: "us-east-1"
      register: ec2_info

    - name: Afficher les informations des instances EC2
      debug:
        var: ec2_info.instances